### ISSUE TITLE
I could not understand the prayers in Arabic

### ISSUE THREAD

**Issue by duran004** [voku/portable-ascii#100]
vendor\voku\portable-ascii\src\voku\helper\data\x0fd.php I don't understand the Arabic prayers in some of the files, why did you put them there? 
![image](https://github.com/voku/portable-ascii/assets/132943905/e08c0e70-78ef-45d9-b1bd-177b5df0f80f)
Is this package doing ASCII char handling or is it praying that our project doesn't crash?

**Comment by voku** [comment]
This is only the fallback, so that we have only ASCII chars, I think you look for this mapping: https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L1665

PS: I just copy&pasted this fallback mapping from perl: https://metacpan.org/release/SBURKE/Text-Unidecode-1.30/source/lib/Text/Unidecode/xfd.pm
