### ISSUE TITLE
Is Georgian to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#13]
Example: Is this correct? 

"ბავშვები" -> "bavshvebi"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L431

**Comment by waska14** [comment]
Hello, @voku 
I'm a native speaker.
The example is 100% correct.

But can you replace file **src/voku/helper/data/ascii_by_languages.php** 
line **981** 
`        'ქ' => 'k',` with `        'ქ' => 'q',`
and line **983** 
`        'ყ' => 'q',` with `        'ყ' => 'y',`
because that letters are incorrect.

**Comment by voku** [comment]
@waska14 Thanks for your help! :1st_place_medal: 

ASCII mapping is updated: https://github.com/voku/portable-ascii/commit/ae0e10660e3b1e40e2c3c923c2de854e83a46a1c

**Comment by waska14** [comment]
@voku Can you also upgrade the version, please?

**Comment by voku** [comment]
v1.5.3 | https://github.com/voku/portable-ascii/blob/master/CHANGELOG.md
