### ISSUE TITLE
Is French to ASCII correct?

### ISSUE THREAD

**Issue by voku** [voku/portable-ascii#31]
Example: Is this correct? 

"français" -> "francais"

---

Can a native speaker, please check the character-replacement, thanks.

https://github.com/voku/portable-ascii/blob/master/src/voku/helper/data/ascii_by_languages.php#L1055

**Comment by GrahamCampbell** [comment]
The link there shows an empty list of replacements?

**Comment by voku** [comment]
:/ because it's implicit defined by other languages, I will fix that.

**Comment by Sharptsa** [comment]
French native speaker here.

It's definitely missing `Î`, `ü` and `Ü`.

For the rest, as everything that has to do with language, it's complicated. 
Because of words borrowed from other languages, some unusual diacritics can be found.

You can check this table : https://fr.wikipedia.org/wiki/Diacritiques_utilis%C3%A9s_en_fran%C3%A7ais#Combinaisons
Everything in green are "official" signs.
Everything in orange and signs that are uncommon but exist in at least one french dictionnary.

From personnal experience and some examples in this Wikipedia article, `ä`, `ÿ` and `ö` (and their uppercase counterpart) seem to be the least uncommon of the orange list.

I leave it up to you to choose those that should be added, but I think a good compromise would be to remove `Á` `á`, and add  `ä` `Ä` `ÿ` `Ÿ` `ö` `Ö`.

**Comment by voku** [comment]
@Sharptsa Thanks for the suggestions. Can you please re-review the changes, thanks. https://github.com/voku/portable-ascii/blob/267e1c600bc694b0360493c2152fa748df3387b5/src/voku/helper/data/ascii_by_languages.php#L1260

**Comment by Sharptsa** [comment]
Looks good to me.

**Comment by Sharptsa** [comment]
Woops, I was so focused on diacritic I forgot to mention the `æ` ligature should also be added.
```
'Æ' => 'AE',
'æ' => 'ae',
```

**Comment by voku** [comment]
@Sharptsa ```æ``` is also added and thanks for the re-review. :1st_place_medal:
